BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
BB BBBBBBBB
    BBB BBBBBBB BB BBBBBBBB
        XXXX BB BBBBBBBBBBBB BB BBBBBBB XXXXXXXXXXXX XXXXXXXXXXXXX BBBB
                                              XXXXXXXXXXXX XXXXXXX BBBBBX
            XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
        XXXXXX
    BBBBBB
BBBBB
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX
                     XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
                        BBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX
                      XXXXXX
                     XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX  XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                      XXXXXX
                     XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX  XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                      XXXXXX

                    XXXXXXX

                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
BBBBBBBB