BBBB BBBBBB
XXXXXXXXX XXXXX

XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXX XXXXXX XXXX XXXXXXXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXX X XXXXXXXXXXXXX

    XXXX XXXXXXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXX XXXX XXXXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXXXX XXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
XXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
XXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXX XX XXXXXXXXX XXXXX
                    BBBBBBBBBB
                    BB BBBBBBBB
                        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                            BBB BBBBBBB BB BBBBBBBB
                                XXXXXBB BBBBBBBBBBBB XXXXXXXXXXXX XXXXXXXBBBBBXXXXXXXX
                            BBBBBB
                        XXXXXX
                    BBBBB
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX

                        XXXXX
                            XXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXX XXX XXXXXX XXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXXXXXX
        XXXXXX


    XXXXXX
XXXXXX
XXXXXXX
XXXXXXX
