# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-17 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_base.City'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 21, 21, 915388, tzinfo=utc)),
        ),
    ]
